---
apiVersion: apps/v1
kind: Deployment
metadata: { name: homepage }
spec:
  replicas: 1
  selector: { matchLabels: { app: homepage } }
  template:
    metadata: { labels: { app: homepage } }
    spec:
      serviceAccountName: homepage
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homepage-nfs-pvc
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.kiwilab.dev"
          volumeMounts:
            - name: config
              mountPath: /app/config
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
