---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homepage-nfs-pvc
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.kiwilab.dev"
          volumeMounts:
            - name: config
              mountPath: /app/config
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
