apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
  namespace: speedtest
  labels:
    app: speedtest-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-exporter
  template:
    metadata:
      labels:
        app: speedtest-exporter
    spec:
      containers:
      - name: speedtest-exporter
        image: miguelndecarvalho/speedtest-exporter:latest
        ports:
        - containerPort: 9798
        resources:
          requests:
              memory: "64Mi"
              cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 9798
          initialDelaySeconds: 10
          periodSeconds: 30