apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
  labels:
    app: speedtest-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
    spec:
      containers:
      - name: speedtest-tracker
        image: lscr.io/linuxserver/speedtest-tracker:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Europe/Berlin
        - name: APP_URL
          value: https://speedtest.kiwilab.dev
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: speedtest-env
              key: APP_KEY
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: speedtest_tracker
        - name: DB_USERNAME
          value: speedy
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-speedtest-password
              key: DB_PASSWORD
        - name: SPEEDTEST_SCHEDULE
          value: "0 */4 * * *"
        - name: APP_URL
          value: "https://speedtest.kiwilab.dev"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: speedtest-env
              key: APP_KEY
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - containerPort: 80
          name: http
        resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: speedtest-tracker-pvc
