apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-exporter
  namespace: speedtest
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: speedtest-exporter
  namespaceSelector:
    matchNames:
    - speedtest
  endpoints:
  - port: http
    interval: 4h