apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: speedtest
  labels:
    app: speedtest-exporter
spec:
  ports:
  - name: http
    port: 9798
    targetPort: 9798
  selector:
    app: speedtest-exporter