apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-values
  namespace: crowdsec
data:
  values.yaml: |
    config:
      acquisition:
        volumes:
          - name: acquisition-volume
            configMap:
              name: crowdsec-acquisition
        mountPath: /etc/crowdsec/acquis.yaml
        subPath: acquisition.yaml
      data_dir: /var/lib/crowdsec/data

    agent:
      acquisition:
        - namespace: ingress-nginx
          podName: ".*"
          containerName: ".*"
          program: nginx
      containerSecurityContext:
        privileged: true

    dashboard:
      enabled: true
      ingress:
        enabled: true
        className: nginx
        hosts:
          - host: dashboard.kiwilab.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - dashboard.kiwilab.dev
            secretName: crowdsec-dashboard-tls