apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: crowdsec
  releaseName: crowdsec
  chart:
    spec:
      chart: crowdsec
      version: 0.19.3
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
  values:
    agent:
      container_runtime: containerd
      log_level: debug
      acquisition:
        - namespace: ingress-nginx
          podName: ingress-nginx-controller-*
          program: nginx
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
    lapi:
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 150m
          memory: 100Mi
      persistentVolume:
        data:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: ""
          existingClaim: ""
          size: 1Gi
        config:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: ""
          existingClaim: "lapi-crowdsec-pvc"
          size: 1Gi