# infrastructure/crowdsec/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 10m
  releaseName: crowdsec
  targetNamespace: crowdsec
  chart:
    spec:
      chart: crowdsec
      version: 0.19.3
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: crowdsec
  valuesFrom:
    - kind: ConfigMap
      name: crowdsec-values
      valuesKey: values.yaml