apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: crowdsec
  releaseName: crowdsec
  chart:
    spec:
      chart: crowdsec
      version: 0.19.3
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
  values:
    agent:
      container_runtime: containerd
      acquisition:
        - namespace: ingress-nginx
          podName: ingress-nginx-controller-*
          program: nginx
          # If the agent still doesn't pick up logs automatically, you might need to specify exact paths:
          # paths: ["/var/log/nginx/access.log", "/var/log/nginx/error.log"]
      # Ensure CrowdSec agent runs on the master node if NGINX is only on master
      # Add these tolerations if your master node has a 'NoSchedule' taint
      # (This is common for master nodes, and your NGINX ingress controller already has this)
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      extraVolumes:
        - name: host-nginx-logs
          hostPath:
            path: /var/log/nginx
            type: DirectoryOrCreate
      extraVolumeMounts:
        - name: host-nginx-logs
          mountPath: /var/log/nginx
          readOnly: true
    lapi:
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 150m
          memory: 100Mi
      persistentVolume:
        data:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: ""
          existingClaim: ""
          size: 1Gi
        config:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: ""
          existingClaim: "lapi-crowdsec-pvc"
          size: 1Gi