apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: flux-system
spec:
  interval: 10m
  releaseName: crowdsec
  targetNamespace: crowdsec
  install:
    createNamespace: true
  chart:
    spec:
      chart: crowdsec
      version: 0.19.3
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
  values:
    container_runtime: containerd

    lapi:
      enabled: true

    agent:
      acquisition:
        - namespace: ingress-nginx
          podName: ingress-nginx-controller-*
          program: nginx
      env:
        - name: COLLECTIONS
          value: crowdsecurity/nginx
