---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/ingress.yaml
  - base/rbac.yaml
  - storage/homepage-pvc.yaml
  - cloudflare-api-token-secret.sops.yaml
