---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim-server
  namespace: valheim
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: valheim
  template:
    metadata:
      labels:
        app: valheim
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: k8s-worker01
      containers:
        - name: valheim
          image: ghcr.io/lloesche/valheim-server
          ports:
            - containerPort: 2456
              protocol: UDP
            - containerPort: 2457
              protocol: UDP
            - containerPort: 2458
              protocol: UDP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /opt/valheim
          envFrom:
            - configMapRef:
                name: valheim-env
          env:
            - name: SERVER_PASS
              valueFrom:
                secretKeyRef:
                  name: valheim-secret
                  key: SERVER_PASS
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "6Gi"
              cpu: "2000m"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: valheim-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: valheim-data-pvc
