---
apiVersion: v1
kind: Service
metadata:
  name: valheim-service
  namespace: valheim
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: valheim
  ports:
    - name: valheim-udp1
      port: 2456
      targetPort: 2456
      protocol: UDP
      nodePort: 31670
    - name: valheim-udp2
      port: 2457
      targetPort: 2457
      protocol: UDP
      nodePort: 31671
    - name: valheim-udp3
      port: 2458
      targetPort: 2458
      protocol: UDP
      nodePort: 31672
    - name: status
      port: 9001
      targetPort: 9001
      protocol: TCP
      nodePort: 31673
