---
# Satisfactory
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: satisfactory
  namespace: flux-system
spec:
  interval: 10m
  path: ./gameserver/satisfactory
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: satisfactory