apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/ingress.yaml
  - storage/pv-vaultwarden.yaml
  - secret.sops.yaml
 # - secret-smtp.sops.yaml