---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: valheim-config-pv
  namespace: valheim
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/valheim/config
    type: DirectoryOrCreate
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-config-pvc
  namespace: valheim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: valheim-data-pv
  namespace: valheim
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/valheim/data
    type: DirectoryOrCreate
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-data-pvc
  namespace: valheim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
