# google.yaml
apiVersion: v1
kind: Service
metadata:
  name: probe-google
  namespace: monitoring
  labels:
    blackbox: probe-targets
spec:
  type: ExternalName
  externalName: www.google.com
  ports:
    - name: http
      port: 80