apiVersion: v1
kind: Service
metadata:
  name: probe-google
  namespace: monitoring
  labels:
    blackbox: probe-targets
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: probe-google
  namespace: monitoring
subsets:
  - addresses:
      - ip: 142.250.185.4
    ports:
      - port: 80
