apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-admin-token
    namespace: vaultwarden
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:lbJPh0KJsbnjG7FyZGmFaJMedso7tpRT3a0K+lqnLIZTh4PaUdLk9WnpNcG6k8nzzJ26wg7Hh2mmENKWBi2bz/jA6Udilwpt0Qj5/w==,iv:Glu81FBCda0HQh4lAuLxq69+59f1xMzSvbrZ8H+rRuk=,tag:lmPa96R4se7UnbEXtMkgTg==,type:str]
sops:
    age:
        - recipient: age17ts7pfxmpkv4xcr37dr3r2929vn0k8aaht8h94eexvqkkuv3nd6sp0l3y6
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVd0UzenNnMUJWdmRxeWI4
              TU5mdHdpNEc4YXNOeUcyTENFWWVJL0QyMnlnCkNwZ3hVUGl5eHBYb2MzWFdIZ1ha
              QkxuYUJuZnJxMU5Vc21vWFZ5RFhJMXcKLS0tIEM4blFUVEE2dTJzMThlQmR4T24r
              OFg2MXBaZVJVZXZVYnZmQndrUTU5ZTAKkMvuPJXxdqHhc+dBgUn5LiU5H/Qd+7c1
              rmwT1nfBfkxp/NK0teRvBTD91mHNKJ3I1FqO0Dqq+kXNYudHoJOsmQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T21:09:24Z"
    mac: ENC[AES256_GCM,data:E5CV3M4OgjcGAzZjGAps88+VZ99ViWGbuhU0/fc07hJvxwH5EYJCGMA0SHZOe+VBY3/EbDBBh0F/9X+uGCgwS0ZCs9vEm6UjjxP4n3MLmOTVXQlZM0c8VwBzeoIkvgTDqAmAuAl04i2QENd77o3C5eSskegku3i8NEqmtZI7Q4U=,iv:UrTzSWbnf2eImPchtqqRNnSH90uzxyF1qQQdhJIQqVc=,tag:GJtiNYNFB49JDR41HqZGfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
