apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-smtp-secret
    namespace: vaultwarden
type: Opaque
stringData:
    smtp-password: ENC[AES256_GCM,data:VvE4/NEYxTfHNE7W+TurIA==,iv:2Zt+IJKvvYGsz2pRe1KUYfBHvO9DLpuOYC8hl1l0eRM=,tag:LbpG+XSXuSb4AUXs3ubvmg==,type:str]
sops:
    age:
        - recipient: age17ts7pfxmpkv4xcr37dr3r2929vn0k8aaht8h94eexvqkkuv3nd6sp0l3y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUkhRQTNZYTRhNWQ4Yllt
            bjNiTU10ZWE3SDJkRVJXeW9VeGtPdStpMFVzCm92eVVOUjNnVUxZaTFyQnczZzg3
            SEU3ZFp3U1JMci9tRUxjMnUvRHhwVG8KLS0tIHB6a2srSVJ4YWpqQTNxZTRUSVBo
            Sjd3VHhPWmVLOVlNSmtPWHlJVVU4ZncKIPRyd1XYKVHblvixIQeEtOAq+weaEV0M
            ES6RNISmpDRJSNwEJiKoqbDgta3/SRDnwZ1pF4YQ0Qw9nyGkrQXtVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T22:03:24Z"
    mac: ENC[AES256_GCM,data:MAi2de+dEB+CzosTCKLwT590bW9/UpKbZAQOeqoEPcuqCQcUwxgij+FSpsyS0Xh6Xf658kBTdj6wGT0aFX02/4nJiMTfJHLJ8mB0JZacJ7M1uj2dH0DjtP4dHgdBO1d4DJu+/nflXD+4iSv6aPHBHpO0tfIQPxGxebYz3G1Jnig=,iv:nAi7yEOmVobCaz/ApNhhmvTWBzJPhE43Uqgvz9F9mHY=,tag:1McWy2YRg5+rShA0UiJ0hA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
