apiVersion: v1
kind: PersistentVolume
metadata:
  name: lapi-crowdsec-pv
  namespace: crowdsec
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.178.200
    path: /srv/k8s-data/crowdsec
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lapi-crowdsec-pvc
  namespace: crowdsec
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""