apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ENC[AES256_GCM,data:gb7wzZFv+I+KujWZTE3tZNO2P2mCctfEzg==,iv:AJns1QrP4Xv/V1a9y2UL/yy1hwhM1LYb6kcx0Fg2eWs=,tag:M+ze//2/HIyifi/prTmnSQ==,type:str]
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
sops:
  age:
    - recipient: age17ts7pfxmpkv4xcr37dr3r2929vn0k8aaht8h94eexvqkkuv3nd6sp0l3y6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5c1JBNW05akc3UnpJNDRm
        ei9nQnJvakRVcUJxcnA4SG5uQm0wS3BZVVdJClNwNkpraFNTTWVTZDNTc1A1djlI
        TFhRUGJ1WE9YOHIydElpanRKc2Iva1UKLS0tIEp5T2RGbU5scVJVU1N5TXZpNUdz
        NUZaRUc5ZGZ4QVkxbjdJZHdndTQ1VUkKpXM3yTOtts5/9/3qVAEuluIhvON2ye2s
        U+JJrzJvlXZTd6U64k2OROKkPZU0vf5YL9t0iVUNpr2USzujZgHz9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-12T18:40:23Z"
  mac: ENC[AES256_GCM,data:wlemgnBBLInAvU/p+m8tbqzvOXgjENiht0GPw4U57mJnzoh3BIItGvSdG3UUPLAHN8VjzEtdHA1LcYpLM/DkDdWYbr33CRaPPeqA8YagrI610WmlvOTQIDbafIJcyAdjhn64zWQXKtH0K6wWcSOfvYtcdSYulhHS0DkbzvhwKBg=,iv:3ORPRH8nDZlXBpzlNrr5LRaPRA9lyzrwIoyBbDHbzag=,tag:NiQoMf1LWRSuSNv3QIh5Lg==,type:str]
  encrypted_regex: ^(email)$
  version: 3.10.2
