---
# staging issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: server.mehlhorn@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
sops:
  age:
    - recipient: age17ts7pfxmpkv4xcr37dr3r2929vn0k8aaht8h94eexvqkkuv3nd6sp0l3y6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VWR4N2UzNXpmWjBCNjdq
        UDZuSTRPYmNCcHJvMGpPM05UeGNmU05PUmpRCmViUHE1TFA5SU9yM2ZxaDVqSlEr
        NURIdHBaRktqMnV5SWo1KzdweTkzT2sKLS0tIGt4eFYzc1EyT0wwekJZNTAxdk8v
        RlFBZTU5VGVKeFZDeUxINkVJNm5jNUkK85S+TiRfgZp0LR+YieA5GLiRpQvEUb78
        /CVlBGAGP07cLmw7iETXzl9uEQ/LrMQDWRQYVvGLn7LbrU6UfY7KGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-17T16:39:56Z"
  mac: ENC[AES256_GCM,data:duPF0z2EYPnMd3/9urq7OcDYr727BV2wM0FHpezRtqihydfTsjD3auQ07zGGj2gqMp3qyiuL75e/RfSnJX5Esg6eE7uYcxy59cd2WQaNV665pSN3jXkRagUGJchADK4PH1cGGbz5eaLxRSPrjrGE7f8X666GHpNbMjP5hIfqcR8=,iv:olefNXc5PM6qqwFqpSy3BmrrQBKp9gU4IF69jqtwjDY=,tag:PZNxr9jcN7ECtJhhwvzQWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
