# staging issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ENC[AES256_GCM,data:GALpPrhpEJlItv3f0+uyAWfdNF0w7CvFBA==,iv:7dznDMHgkRVd3q6jW+VXoyTbIcw5OwYc2gUbmlcI7eo=,tag:wX6KQYH8/O7jVNtkhMQjAw==,type:str]
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
sops:
    age:
        - recipient: age17ts7pfxmpkv4xcr37dr3r2929vn0k8aaht8h94eexvqkkuv3nd6sp0l3y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VFNEVzhZbUZXc0FNaWpw
            Q0x0VWQ1cnhUZktpdzZleFpLSlhrSHc3bW5jCnBLM1lDanY1eUFYRnBOQ2UvcHBI
            UFBxeHo2b2RybWI1VHVOdmwxdFFhN1UKLS0tIDlHaVpGemdMZTBRdkRaaUtMK21Z
            ZDVNeWFBZytiaEZ6bzRNRDFmK0J1S0kKHF5Alrb2/Q/cvDSCgevp4GcWRG42WB5H
            RI0yoQ4RjhHKQUakfX95ChGWkOCWXGKrxVyn1CSw2vPMAJyu+6a35A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T16:16:04Z"
    mac: ENC[AES256_GCM,data:R3RpeGADcnGd/oMuIMPxcjxAcLG7RPY+3z1Ah9kxyCRF56o3SC3Pr1jT3e2gEwy2tO1WKhllBcr6NLgwjGWlpBM1+WZq6WPJYXMdReM8lE6ixrmqTn7GD1MfCH+PYQO1M5OU1FMgU7yxAYsj/leyhABzE/BDaAaDsp2YxrNfX0c=,iv:FBQlS2/jGFh1zryaMwv9kYuCep9+EtAQKpPIRtieqzU=,tag:jHcHuPjKY2hCuFU2B5Vx6A==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2