---
apiVersion: v1
kind: Service
metadata:
  name: vrising-service
  namespace: vrising
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: vrising
  ports:
    - name: vrising-udp1
      port: 9876
      targetPort: 9876
      protocol: UDP
      nodePort: 31674
    - name: vrising-udp2
      port: 9877
      targetPort: 9877
      protocol: UDP
      nodePort: 31675
