apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/ingress.yaml
  - storage/speedtest-tracker-pvc.yaml
  - secrets/secret.sops.yaml
  - secrets/admin-pw.sops.yaml
  - secrets/email.sops.yaml
