---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-nfs-pv
  namespace: homepage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.178.200
    path: /srv/k8s-data/homepage
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-nfs-pvc
  namespace: homepage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
