---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: YOUR_NFS_SERVER
    path: /export/homepage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
