---
# Wiki.js PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-nfs-pv
  namespace: wiki
  labesl:
    app.kubernetes.io/name: wiki
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.178.200
    path: /srv/k8s-data/wiki
---
# Wiki.js PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-nfs-pvc
  namespace: wiki
  labels:
    app.kubernetes.io/name: wiki
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
