---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory-server
  namespace: satisfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      nodeSelector:
        environment: gameserver
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:latest
          ports:
            - containerPort: 7777
              protocol: TCP
            - containerPort: 7777
              protocol: UDP
            - containerPort: 8888
              protocol: TCP
          env:
            - name: MAXPLAYERS
              value: "4"
            - name: PGID
              value: "1001"
            - name: PUID
              value: "1001"
            - name: STEAMBETA
              value: "false"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: satisfactory-pvc
