---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory-server
  namespace: satisfactory
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
        app.kubernetes.io/name: satisfactory
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: k8s-worker01
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:latest
          args:
            - "-ini:Engine:[SystemSettings]:FG.DedicatedServer.AllowInsecureLocalAccess=1"
          ports:
            - containerPort: 7777
              protocol: TCP
            - containerPort: 7777
              protocol: UDP
            - containerPort: 8888
              protocol: TCP
          env:
            - name: MAXPLAYERS
              value: "4"
            - name: PGID
              value: "1001"
            - name: PUID
              value: "1001"
            - name: STEAMBETA
              value: "false"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "12Gi"
              cpu: "1"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: satisfactory-pvc
