---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory-server
  namespace: satisfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker01
      initContainers:
        - name: init-ssl
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /config/ssl
              cp /secret/* /config/ssl/
              chown -R 1001:1001 /config/ssl
          volumeMounts:
            - name: tls
              mountPath: /secret
            - name: config
              mountPath: /config
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:latest
          args:
            - "-HttpsServerCertChainFile=/config/ssl/tls.crt"
            - "-HttpsServerKeyFile=/config/ssl/tls.key"
          ports:
            - containerPort: 7777
              hostPort: 7777
              protocol: TCP
            - containerPort: 7777
              hostPort: 7777
              protocol: UDP
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          env:
            - name: MAXPLAYERS
              value: "4"
            - name: PGID
              value: "1001"
            - name: PUID
              value: "1001"
            - name: STEAMBETA
              value: "false"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tls
              mountPath: /config/ssl
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "12Gi"
              cpu: "1"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: satisfactory-pvc
        - name: tls
          secret:
            secretName: satisfactory-tls
