---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory-server
  namespace: satisfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: k8s-worker01
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:latest
          ports:
            - containerPort: 7777
              protocol: TCP
            - containerPort: 7777
              protocol: UDP
            - containerPort: 8888
              protocol: TCP
          env:
            - name: MAXPLAYERS
              value: "4"
            - name: PGID
              value: "1001"
            - name: PUID
              value: "1001"
            - name: STEAMBETA
              value: "false"
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
            limits:
              memory: "12Gi"
              cpu: "1000m"
          livenessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: satisfactory-pvc
