---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-satisfactory
  namespace: satisfactory
spec:
  schedule: "6 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command: ["sh", "-c", "kubectl rollout restart deployment/satisfactory-server -n satisfactory"]
