---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
        app.kubernetes.io/name: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          ports:
            - containerPort: 80
          env:
            - name: DATA_FOLDER
              value: "/data"
            - name: WEBSOCKET_ENABLED
              value: "true"
            - name: SIGNUPS_ALLOWED
              value: "false"
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-admin-token
                  key: admin-token
            - name: ENABLE-RATE-LIMIT
              value: "true"
            - name: RATE-LIMIT-SECONDS
              value: "60"
            - name: RATE-LIMIT-MAX-BURST
              value: "10"
            - name: DOMAIN
              value: "https://vault.kiwilab.dev"
            - name: URL_BASE
              value: "https://vault.kiwilab.dev"
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "465"
            - name: SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: email
                  key: EMAIL
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email
                  key: EMAIL
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-smtp-secret
                  key: smtp-password
            - name: SMTP_SSL
              value: "true"
            - name: SMTP_STARTTLS
              value: "false"
            - name: SMTP_EXPLICIT_TLS
              value: "true"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: vaultwarden-data
              mountPath: /data
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-nfs-pvc
