apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: internet-icmp
  namespace: monitoring
  labels:
    release: prometheus
spec:
  jobName: "icmp"
  interval: 60s
  module: icmp
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 1.1.1.1
        - 8.8.8.8