apiVersion: v1
kind: Service
metadata:
  name: postgres-wiki-service
  namespace: wiki
spec:
  selector:
    app: postgres-wiki
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
