---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  selector:
    app: speedtest-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
