apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-tracker
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: speedtest-tracker
  namespaceSelector:
    matchNames:
      - speedtest-tracker
  endpoints:
    - port: http
      path: /metrics
      interval: 60s