---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: monitoring
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "73.2.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: "local-path"
              resources:
                requests:
                  storage: 20Gi
        additionalScrapeConfigs: |
          - job_name: 'crowdsec'
            static_configs:
              - targets: ['192.168.178.200:6060']
          - job_name: 'blackbox'
            metrics_path: /probe
            params:
              module: [http_2xx]
            static_configs:
              - targets:
                - https://www.google.com
                - https://prometheus.io
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
    alertmanager:
      enabled: false
