apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-targets
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 30s
      port: http
      path: /probe
      params:
        module: [http_2xx]
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.blackbox-exporter.svc.cluster.local:9115
  selector:
    matchLabels:
      blackbox: probe-targets
  namespaceSelector:
    matchNames:
      - monitoring