apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wiki
resources:
  - namespace.yaml
  - pv.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - wiki/deployment.yaml
  - wiki/service.yaml
  - wiki/ingress.yaml