apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wiki
resources:
  - storage/pv-postgres.yaml
  - storage/pv-wiki.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/ingress.yaml
  - secrets/secret.sops.yaml
