apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-nginx-config
  namespace: ingress-nginx
data:
  crowdsec-auth.conf: |
    auth_request /crowdsec-auth;

    location = /crowdsec-auth {
        internal;
        proxy_pass http://crowdsec-lapi.crowdsec.svc.cluster.local:8080/api/v1/nginx;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
