apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      replicaCount: 1
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      service:
        type: LoadBalancer

      extraContainers:
        - name: crowdsec-bouncer
          image: crowdsecurity/openresty:latest
          env:
            - name: CROWDSEC_BOUNCER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: crowdsec-bouncer-secret
                  key: api-key
            - name: CROWDSEC_LAPI_URL
              value: http://k8s-master.local:8080/
            - name: GIN_MODE
              value: release
          ports:
            - containerPort: 8080
              name: bouncer-port

      extraVolumes:
        - name: nginx-config
          configMap:
            name: custom-nginx-config

      extraVolumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
