---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      replicaCount: 1
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      service:
        type: LoadBalancer
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        enable-real-ip: "true"
        real-ip-header: "X-Forwarded-For"
        set-real-ip-from: "0.0.0.0/0"
        plugins: "crowdsec"
        lua-shared-dicts: "crowdsec_cache: 50m"
        resolver: "192.168.178.200"
        add-headers: /etc/nginx/conf.d/security-headers.conf
      extraVolumes:
        - name: nginx-config
          configMap:
            name: custom-nginx-config
        - name: nginx-logs
          hostPath:
            path: /var/log/nginx
            type: DirectoryOrCreate
        - name: crowdsec-bouncer-plugin
          emptyDir: {}
      extraInitContainers:
        - name: init-clone-crowdsec-bouncer
          image: crowdsecurity/lua-bouncer-plugin:v1.0.5
          imagePullPolicy: IfNotPresent
          env:
            - name: API_URL
              value: "http://192.168.178.200:8080"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: crowdsec-nginx-bouncer-api-key
                  key: api-key
            - name: BOUNCER_CONFIG
              value: "/crowdsec/crowdsec-bouncer.conf"
          command:
            - "sh"
            - "-c"
            - >
              /docker_start.sh && mkdir -p /lua_plugins/crowdsec/ && cp -R /crowdsec/* /lua_plugins/crowdsec/
          volumeMounts:
            - name: crowdsec-bouncer-plugin
              mountPath: /lua_plugins
      extraVolumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: crowdsec-bouncer-plugin
          mountPath: /etc/nginx/lua/plugins/crowdsec
          subPath: crowdsec
