---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/valheim-env.yaml
  - storage/pv-valheim.yaml
  - valheim-secret.sops.yaml
