apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: monitoring
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: "7.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    installCRDs: true
    persistence:
      enabled: true
      type: pvc
      existingClaim: grafana-nfs-pvc
      storageClassName: ""
      size: 5Gi