apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-issuer
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infrastructure/cert-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: cert-manager
