- name: wiki
  namespace: flux-system
  path: ./apps/wiki
  prune: true
  targetNamespace: wiki
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
