apiVersion: ENC[AES256_GCM,data:FRA=,iv:lE69LGn0UZHYDwav6arG4zXBUfrJ/IqOvKBp3PO/HMM=,tag:BSwaRCY6bWcLhfL+fmzscg==,type:str]
kind: ENC[AES256_GCM,data:Ho6+o18t,iv:v0JIGIhBj6jNRSab7BmoTTlQx/E8fLrV0OaiKeQo9Bc=,tag:vIXmO4U7/K2pVMkzcQLizg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sakvHUxd+CP2oIxGuceFApOLaQL3AqqeOjwfzgJK,iv:xjShVBVVQPQRW1X1/lrXQiLdTZEgwXdColSZ7mDaOYY=,tag:+6xxR5GO4sb6TGLb8UPjfA==,type:str]
    namespace: ENC[AES256_GCM,data:KlhkjDG7stssO7JG1g==,iv:7+7u67P6GOUzjwjfBwULE9dcfcscEiM8XYsFjRbncso=,tag:nQMNX32dWAqvUwR4KTtpoA==,type:str]
type: ENC[AES256_GCM,data:qRoci/g/,iv:2+r+0BYn66MtW3MW+wiOZCK1+SZyD8WDU/FC0uzvlyo=,tag:MX1assk7Lh5CJyk6sYeVag==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:Bs3h0pMxgAuEhrFZnuITU6AfPbyDdRUCM20d80FLyW+PnctSKFGNeljTAQ==,iv:MF9vNUxjMoK61h/W3kPXPmmsZMBnDZZadCe3p/NEbFM=,tag:9X/vDEcee08fuGneMirNDQ==,type:str]
sops:
    age:
        - recipient: age17ts7pfxmpkv4xcr37dr3r2929vn0k8aaht8h94eexvqkkuv3nd6sp0l3y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UHk0bVZLSk04RFRROGZY
            MitKcnJwdTdQaFNJMXR0Y2grSUxQOFVYY0VjClpGUDh3bytTYUxwWWd1Rk5SLzVF
            VGdGdmdhcmhsWUpYT0tVNk9qeWRZTlEKLS0tIGFsdERmbDAwNEpWc0x1bmhyVDY0
            TXc4VnJQOGhhK05VTC91Z1dhb3dEMGsKONRltEUJsu91vP5I5mt+CfGqKRzDcs+O
            l0HUHd11Yw7bVlYOeviLCpUO8gLlVe0mdvnj1y8pcvhnLvAEQLhILA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T22:00:12Z"
    mac: ENC[AES256_GCM,data:MdJopNWRXnPAUTCiP0fooUmyknhEeExRkz0ly9nBF/id2QQfzjYuVyaVAwrx9DfIuYoGFFwdzPynrTdfB6RPgMiIHT1dw5Se4Wf/ndAQvaC3Cuys1Y+3ea3wEHYkmWaXgusIeYtQXnlfi+gQ1+AYAHxVajt4PDQMQb7179UVeDk=,iv:OsuoMXJGfZ6wDryQBIkeNcSgXHNLhkloR/AM5c7RR0g=,tag:BKe1q6RiMPFb2U3szc1P+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
