apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/helmrelease.yaml
  - base/helm-repo.yaml
  - base/namespace.yaml

configMapGenerator:
  - name: crowdsec-values
    files:
      - config/crowdsec-values.yaml
  - name: crowdsec-acquisition
    files:
      - config/acquisition.yaml
generatorOptions:
  disableNameSuffixHash: true