---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: satisfactory-pv
  namespace: satisfactory
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.178.200
    path: /srv/k8s-data/satisfactory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-pvc
  namespace: satisfactory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
