---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: satisfactory-self-tls
  namespace: satisfactory
spec:
  secretName: satisfactory-tls
  commonName: dummy.local
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
