---
name: Validate Kubernetes YAML

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg yamllint wget

          # yamllint disable-line rule:line-length
          wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.6.0/kustomize_v5.6.0_linux_amd64.tar.gz

          tar -xzf kustomize_v5.6.0_linux_amd64.tar.gz
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/

      - name: Lint YAML files
        run: |
          find . -type f -name "*.yaml" ! -name "*.sops.yaml" | xargs -r yamllint || exit 1

      # Kustomize build steps for Flux System
      - name: Build Flux System Kustomization
        run: kustomize build clusters/heimdall/flux-system > /dev/null

      # Kustomize build steps for Applications
      - name: Build Wiki Kustomization
        run: kustomize build ./apps/wiki > /dev/null

      - name: Build Vaultwarden Kustomization
        run: kustomize build ./apps/vaultwarden > /dev/null

      - name: Build Speedtest Kustomization
        run: kustomize build ./apps/speedtest > /dev/null

      # Kustomize build steps for Gameserver
      - name: Build Satisfactory Kustomization
        run: kustomize build ./gameserver/satisfactory > /dev/null

      - name: Build Valheim Kustomization
        run: kustomize build ./gameserver/valheim > /dev/null

      # Kustomize build steps for Infrastructure
      - name: Build Ingress-Nginx Kustomization
        run: kustomize build ./infrastructure/ingress-nginx > /dev/null

      - name: Build Cert-Manager Kustomization
        run: kustomize build ./infrastructure/cert-manager > /dev/null

      - name: Build Cert-Issuer Kustomization
        run: kustomize build ./infrastructure/cert-issuer > /dev/null

      - name: Build Grafana Kustomization
        run: kustomize build ./infrastructure/monitoring/grafana > /dev/null

      - name: Build Prometheus Kustomization
        run: kustomize build ./infrastructure/monitoring/prometheus > /dev/null

      - name: Build Blackbox Kustomization
        run: kustomize build ./infrastructure/monitoring/blackbox > /dev/null
