# .github/workflows/validate.yaml
name: Validate Kubernetes YAML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg yamllint
          curl -Lo kustomize https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize_linux_amd64
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/

      - name: Lint YAML files
        run: |
          find . -name "*.yaml" -o -name "*.sops.yaml" | xargs -r yamllint || exit 1

      - name: Build kustomize (fail if invalid)
        run: kustomize build clusters/heimdall > /dev/null
