apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    replicaCount: 1
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    hostPort:
      enabled: true
    nodeSelector:
      kubernetes.io/hostname: k8s-master
    service:
      type: ClusterIP
